/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Cola.Cola;
import Modelo.Coche;
import Modelo.Semaforo;
import Modelo.Controlador;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Proceso extends javax.swing.JFrame {

    Cola ColaDerecha = new Cola();
    Cola ColaIzquierda= new Cola();
    Cola ColaBloqueados= new Cola();
    Coche co= new Coche();
    Controlador contro=new Controlador();
    Semaforo semaforo= new Semaforo(0,contro);
    Semaforo semaforo2= new Semaforo(1,contro);
    Imagen imagen= new Imagen();
    public Proceso() {
        
        
        initComponents();
        this.setLocationRelativeTo(null);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        bntDerecha = new javax.swing.JButton();
        btnIzquierda = new javax.swing.JButton();
        btnBloqueados = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        txtColaDerecha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtColaIzquierda = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel1.setBackground(new java.awt.Color(153, 153, 153));

        bntDerecha.setText("Adicionar coche Derecha");
        bntDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDerechaActionPerformed(evt);
            }
        });

        btnIzquierda.setText("Adicionar coche Izquierda");
        btnIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzquierdaActionPerformed(evt);
            }
        });

        btnBloqueados.setText("ver cola Bloqueados");
        btnBloqueados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBloqueadosActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/puente.png"))); // NOI18N

        btnInicio.setText("Inicio");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        txtColaDerecha.setEditable(false);
        txtColaDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColaDerechaActionPerformed(evt);
            }
        });

        jLabel2.setText("Tamaño Cola Derecha");

        jLabel3.setText("Tamaño Cola Izquierda");

        txtColaIzquierda.setEditable(false);

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1))
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtColaIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnBloqueados, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Panel1Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Panel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtColaDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addComponent(bntDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBloqueados, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInicio)
                    .addComponent(txtColaDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtColaIzquierda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDerechaActionPerformed
       
        co = crearCoche();
        if (co.getPeso() >= 600) {
            JOptionPane.showMessageDialog(null, "limite de capacidad excedido " + co.getPeso() + "kg");
            ColaBloqueados.add(co);
        } else {
            JOptionPane.showMessageDialog(null, "Ha ingresado 1 coche a la derecha");
            ColaDerecha.add(co);
            imagen.cargarImagenDe(Panel1.getGraphics());
            //txtpeso.setText(String.valueOf(co.getPeso()));

            System.out.println(ColaDerecha.getLast());
            txtColaDerecha.setText(String.valueOf(ColaDerecha.size()));
        }
    }//GEN-LAST:event_bntDerechaActionPerformed

    private void btnIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzquierdaActionPerformed
        
        
        co = crearCoche();
        if (co.getPeso() >= 600) {
            JOptionPane.showMessageDialog(null, "limite de capacidad excedido " + co.getPeso() + "kg");
            ColaBloqueados.add(co);
        } else {
            JOptionPane.showMessageDialog(null, "Ha ingresado 1 coche a la izquierda");

            ColaIzquierda.add(co);

            imagen.cargarImagenIz(Panel1.getGraphics());

            System.out.println(ColaIzquierda.getLast());
            txtColaIzquierda.setText(String.valueOf(ColaIzquierda.size()));
        }
     
    }//GEN-LAST:event_btnIzquierdaActionPerformed

    private void btnBloqueadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBloqueadosActionPerformed
        JOptionPane.showMessageDialog(null,"Salida por consola");
        System.out.println("-----------------------------Cola blqueados-----------------------------------------------------");
        for (int i = 1; i <=ColaBloqueados.size(); i++) {
            System.out.println(ColaBloqueados.get(i));
      }
        System.out.println("--------------------------------------------------------------------------------------------");
    }//GEN-LAST:event_btnBloqueadosActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        
        
       
        semaforo.start();

        try {
            Thread.sleep(2000);
        } catch (InterruptedException ex) {
            Logger.getLogger(Proceso.class.getName()).log(Level.SEVERE, null, ex);
        }

        if(ColaDerecha.size()==0){
            semaforo2.detener();
        }
        if (ColaIzquierda.size()==0) {
            semaforo.detener();
        }

        
        if (semaforo2.getNombre() == 1) {
            //System.out.println("verde");
            while (ColaDerecha.size() != 0) {
                try {
                    imagen.moverImagenIzq(Panel1.getGraphics());
                    //repaint();
                    System.out.println(ColaDerecha.remove());
                    txtColaDerecha.setText(String.valueOf(ColaDerecha.size()));

                } catch (Exception e) {
                }
            }
        }

        if (semaforo.getNombre() == 0) {
            //System.out.println("rojo");
            while (ColaIzquierda.size() != 0) {
                try {
                    //System.out.println(ColaIzquierda.size());
                    imagen.moverImagenDer(Panel1.getGraphics());
                    //repaint();
                    //JOptionPane.showMessageDialog(null,ColaIzquierda.remove());
                    System.out.println(ColaIzquierda.remove());
                    txtColaIzquierda.setText(String.valueOf(ColaIzquierda.size()));

                } catch (Exception e) {
                }

            }
        }
    }//GEN-LAST:event_btnInicioActionPerformed

    private void txtColaDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColaDerechaActionPerformed
        
    }//GEN-LAST:event_txtColaDerechaActionPerformed

    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proceso().setVisible(true);
                
            }
        });
    }
    
    //public Image imagen;
    public Coche crearCoche(){
        boolean bandera=false;
        
        int peso=1;
        int velocidad=1;
        while(bandera==false){
        peso=(int) (Math.random() * (1400-300)+300);
        if(peso%100==0){
        bandera=true;
        }
      }   
       velocidad=(int)(Math.random()*(21-1)+1); 
       
       Coche c= new Coche(velocidad,peso);
        
        return c;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JButton bntDerecha;
    private javax.swing.JButton btnBloqueados;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnIzquierda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtColaDerecha;
    private javax.swing.JTextField txtColaIzquierda;
    // End of variables declaration//GEN-END:variables

    class Imagen {
       int x=getWidth()/2;
      
      ImageIcon imagen= new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/CocheIz.png")).getImage());
      ImageIcon imagen2= new ImageIcon(new ImageIcon(getClass().getResource("/Imagenes/CocheDer.png")).getImage());
      
      public  void cargarImagenIz(Graphics g){
          g.drawImage(imagen.getImage(),50,100,200,200,null);
      }
      
      public  void cargarImagenDe(Graphics g){
          g.drawImage(imagen2.getImage(),500,200,200,200,null);
         
      }
      
      public  void moverImagenIzq(Graphics g){
           g.setColor(getBackground());
    
          for (int i =500; i >= 50; i-=350) {
                  
                try {
                  g.drawImage(imagen2.getImage(), i, 200, 200, 200, null);
                  Thread.sleep(1000);
                  repaint(600,220,150,200);
              } catch (Exception e) {
              }
              
              
         }
        }
      
      public void moverImagenDer(Graphics g){
          for (int i = 50; i <=500; i+=350) {
              //g.setColor(getBackground());
              try {
                  g.drawImage(imagen.getImage(), i, 100, 200,200, null);
                  Thread.sleep(1000);
                  repaint(50, 100,150,200);
                // repaint();

              } catch (Exception e) {

              }
          }
      }
      
     
    }
    
    
}
